services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    volumes:
      - books:/books
      - metadata:/metadata
      - config:/config
    environment:
      - user=1000:1000
      - Tz=Europe/Madrid

volumes:
  books:
    external: true
  metadata: {}
  config: {}
