services:
  umami:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.umami.loadbalancer.server.port=3000
      - traefik.http.routers.umami.rule=Host(`${FQDN}`)

networks:
  proxy:
    external: true
