services:
  readeck:
    image: codeberg.org/readeck/readeck
    container_name: readeck
    restart: unless-stopped
    init: true
    volumes:
      - data:/readeck
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.readeck.loadbalancer.server.port=8000
      - traefik.http.routers.readeck.entrypoints=https
      - traefik.http.routers.readeck.rule=Host(`${FQDN}`)


volumes:
  data: {}

networks:
  proxy:
    external: true
