services:
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    container_name: whisper
    restart: always
    init: true
    environment:
      ASR_MODEL: large-v1
      ASR_ENGINE: faster_whisper
      ASR_MODEL_PATH: /data/whisper
    volumes:
      - data:/data/whisper
    ports:
      - 9000:9000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  data: {}
