services:
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    init: true
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./unbound.conf:/opt/unbound/etc/unbound/unbound.conf
      - ./conf:/opt/unbound/etc/unbound/unbound.conf.d/
    restart: unless-stopped
