services:
  memos:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.memos.loadbalancer.server.port=5230
      - traefik.http.routers.memos.entrypoints=websecure
      - traefik.http.routers.memos.rule=Host(`${FQDN}`)

networks:
  proxy:
    external: true
