services:
  stirlingpdf:
    container_name: stirlingpdf
    image: stirlingtools/stirling-pdf:latest
    restart: unless-stopped
    init: true
    environment:
      DOCKER_ENABLE_SECURITY: false
      LANGS: es_ES
    volumes:
      - trainingData:/usr/share/tessdata # Required for extra OCR languages
      - extraConfigs:/configs
      - customFiles:/customFiles/
      - logs:/logs/
      - pipeline:/pipeline/
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.stirlingpdf.loadbalancer.server.port=8080
      - traefik.http.routers.stirlingpdf.entrypoints=https
      - traefik.http.routers.stirlingpdf.rule=Host(`stirlingpdf.tuservidor.es`)


volumes:
  trainingData: {}
  extraConfigs: {}
  customFiles: {}
  logs: {}
  pipeline: {}

networks:
  proxy:
    external: true
