services:
  ittools:
    labels:
      - traefik.enable=true
      - traefik.http.services.ittools.loadbalancer.server.port=80
      - traefik.http.routers.ittools.entrypoints=websecure
      - traefik.http.routers.ittools.rule=Host(`${FQDN}`)
